In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4), 10)

In [20]:
myzeros = tf.zeros((4,4))

In [21]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4))

In [23]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=None)

In [25]:
## ----

In [26]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [27]:
sess = tf.InteractiveSession()

In [30]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.3698077   0.76423496 -0.4228374  -1.0936149 ]
 [ 0.3597641  -0.4611133  -2.56707     1.3443614 ]
 [-1.9230305  -1.030992    1.1131189   1.0023384 ]
 [ 0.519719    0.43340656 -0.22287929  0.24046727]]


[[0.47534716 0.20286155 0.33059657 0.7349105 ]
 [0.25346494 0.5116339  0.4847355  0.2435162 ]
 [0.90591466 0.96099365 0.5360929  0.2078613 ]
 [0.5589752  0.94013894 0.02648187 0.3570336 ]]




In [31]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([ [10], [100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a, b)

In [37]:
sess.run(result)

array([[210],
       [430]], dtype=int32)